"""Build the win-rate histogram page from whatever labelled datasets exist.

Form: the job is DISTRIBUTION over an ordinal set of groups, so small multiples -
one histogram per group on a shared x-axis, single hue. Bins are exact: every team
played 24 battles, so win rate takes 25 values (0/24 .. 24/24) and one bin per
value is the honest histogram, not a smoothed approximation.
"""
import json, os
from pathlib import Path
import numpy as np

OUT = Path("/tmp/vgc-pilot/gui/static/hist.html")
NB = 24

def load_ladder():
    p = "/tmp/vgc-pilot/ladder_labels.json"
    if not os.path.exists(p): return None
    d = json.load(open(p))
    groups = []
    for k in range(7):
        w = [v["wins"] for v in d.values() if v["k"] == k]
        if not w: continue
        h = np.bincount(w, minlength=NB + 1).tolist()
        wr = np.array(w) / NB
        groups.append(dict(key=f"k{k}", label=("real team, untouched" if k == 0 else
                        f"{k} of 6 candidates randomised" if k < 6 else "all 6 randomised (random legal team)"),
                        n=len(w), counts=h, mean=float(wr.mean()), median=float(np.median(wr)),
                        p90=float(np.percentile(wr, 90))))
    allw = [v["wins"] for v in d.values()]
    ref = float(np.median([v["wins"] for v in d.values() if v["k"] == 0]) / NB)
    return dict(title="Corruption ladder", sub="real teams with k of six candidates replaced by random legal ones",
                total=dict(n=len(allw), counts=np.bincount(allw, minlength=NB + 1).tolist(),
                           mean=float(np.mean(allw) / NB)), groups=groups, ref=ref,
                ref_label="median untouched real team")

def load_strata():
    p = "/tmp/vgc-pilot/strata_labels.json"
    if not os.path.exists(p): return None
    d = json.load(open(p))
    order = [("real","real team, untouched"),("shuffled","spreads shuffled within species"),
             ("slotcopy1","1 candidate pasted from another real team"),
             ("slotcopy2","2 candidates pasted"),("slotcopy3","3 candidates pasted"),
             ("modeledit","1 candidate regenerated by the model"),
             ("invent","whole team from the model, constrained"),("random","random legal team")]
    groups = []
    for key, label in order:
        w = [v["wins"] for v in d.values() if v["stratum"] == key]
        if not w: continue
        wr = np.array(w) / NB
        groups.append(dict(key=key, label=label, n=len(w),
                           counts=np.bincount(w, minlength=NB + 1).tolist(),
                           mean=float(wr.mean()), median=float(np.median(wr)),
                           p90=float(np.percentile(wr, 90))))
    allw = [v["wins"] for v in d.values()]
    ref = float(np.median([v["wins"] for v in d.values() if v["stratum"] == "real"]) / NB)
    return dict(title="Search-move strata", sub="real teams altered by the moves a search would actually make",
                total=dict(n=len(allw), counts=np.bincount(allw, minlength=NB + 1).tolist(),
                           mean=float(np.mean(allw) / NB)), groups=groups, ref=ref,
                ref_label="median untouched real team")

SECTIONS = [s for s in (load_ladder(), load_strata()) if s]

HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Win rate against the top 50 — distribution</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,600;12..96,800&family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600&display=swap" rel="stylesheet">
<style>
:root{--surface:#fcfcfb;--page:#f9f9f7;--ink:#0b0b0b;--ink2:#52514e;--ink3:#8a8985;--grid:#ebebe8;
 --series:#2a78d6;--series-hover:#3987e5;--rule:#e2e1dd}
@media(prefers-color-scheme:dark){:root{--surface:#1a1a19;--page:#0d0d0d;--ink:#fff;--ink2:#c3c2b7;
 --ink3:#8b8a83;--grid:#2a2a28;--series:#3987e5;--series-hover:#5598e7;--rule:#2f2f2d}}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--page);color:var(--ink);font-family:"IBM Plex Sans",system-ui,sans-serif;
 line-height:1.5;padding:clamp(1.2rem,4vw,3rem);max-width:1100px;margin:0 auto}
h1{font-family:"Bricolage Grotesque",sans-serif;font-weight:800;font-size:clamp(1.3rem,3vw,1.9rem);letter-spacing:-.02em}
.lede{color:var(--ink2);max-width:66ch;margin:.3rem 0 1.6rem;font-size:.92rem}
.controls{display:flex;gap:.6rem;align-items:center;margin-bottom:1.4rem;font-family:"IBM Plex Mono",monospace;font-size:.72rem;color:var(--ink2)}
.controls button{background:var(--surface);color:var(--ink);border:1px solid var(--rule);border-radius:3px;
 padding:.4rem .7rem;font:inherit;cursor:pointer}
.controls button[aria-pressed=true]{border-color:var(--series);color:var(--series)}
.controls button:focus-visible{outline:2px solid var(--series);outline-offset:2px}
section{background:var(--surface);border:1px solid var(--rule);border-radius:4px;padding:1.1rem 1.2rem 1rem;margin-bottom:1.6rem}
h2{font-family:"Bricolage Grotesque",sans-serif;font-weight:600;font-size:1.05rem;letter-spacing:-.01em}
.sub{color:var(--ink2);font-size:.85rem;margin:.1rem 0 1rem}
.panel{display:grid;grid-template-columns:minmax(150px,220px) 1fr;gap:.9rem;align-items:end;
 padding:.35rem 0;border-top:1px solid var(--grid)}
@media(max-width:720px){.panel{grid-template-columns:1fr;gap:.2rem}.lab{padding-bottom:.2rem}}
.panel:first-of-type{border-top:0}
.panel.total{border-top:0;padding-bottom:.7rem;margin-bottom:.35rem;border-bottom:1px solid var(--rule)}
.lab{font-size:.82rem;line-height:1.3;padding-bottom:.7rem}
.lab b{display:block;font-weight:600}
.lab small{display:block;color:var(--ink3);font-family:"IBM Plex Mono",monospace;font-size:.66rem;margin-top:.15rem}
svg{display:block;width:100%;height:96px;overflow:visible}
.chart{min-width:0}
.bar{fill:var(--series);cursor:default}
.bar:hover,.bar:focus{fill:var(--series-hover);outline:none}
.bar:focus-visible{stroke:var(--ink);stroke-width:1}
.grid line{stroke:var(--grid);stroke-width:1}
.axis text{fill:var(--ink3);font-family:"IBM Plex Mono",monospace;font-size:10px}
.peak{fill:var(--ink2);font-family:"IBM Plex Mono",monospace;font-size:10px}
.ref line{stroke:var(--ink2);stroke-width:1}
.ref text{fill:var(--ink2);font-family:"IBM Plex Mono",monospace;font-size:10px}
#tip{position:fixed;pointer-events:none;background:var(--ink);color:var(--surface);font-family:"IBM Plex Mono",monospace;
 font-size:.7rem;padding:.4rem .55rem;border-radius:3px;display:none;z-index:9;white-space:nowrap;line-height:1.35}
table{border-collapse:collapse;width:100%;font-family:"IBM Plex Mono",monospace;font-size:.7rem;margin-top:.6rem}
th,td{text-align:right;padding:.25rem .45rem;border-bottom:1px solid var(--grid)}
th:first-child,td:first-child{text-align:left}
th{color:var(--ink2);font-weight:500}
.hidden{display:none}
.foot{color:var(--ink3);font-size:.78rem;margin-top:.5rem;max-width:72ch}
</style></head>
<body>
<h1>Win rate against the top 50 — distribution</h1>
<p class="lede">Every team played <b>24 battles</b> against opponents drawn from the top-50 meta pool, both sides piloted by
the behaviour-cloning policy. A win rate is therefore one of 25 exact values, and each bar below is one of them —
no smoothing. Panels share the x-axis; y-scales are per panel and the peak count is labelled.</p>
<div class="controls" role="group" aria-label="View">
  <span>view</span>
  <button id="bChart" aria-pressed="true">chart</button>
  <button id="bTable" aria-pressed="false">table</button>
</div>
<div id="root"></div>
<div id="tip" role="tooltip"></div>
<script>
const DATA = __DATA__;
const NB = 24, H = 96, PADL = 6, PADR = 6, PADB = 4;
let W = 760;
const $ = s => document.querySelector(s);
const tip = $("#tip");
const fmtWr = i => (i / NB).toFixed(3);

function panelSVG(g, ref, refLabel, withAxis) {
  const max = Math.max(...g.counts), plotH = H - (withAxis ? 18 : 0);
  const slot = (W - PADL - PADR) / (NB + 1), bw = Math.min(24, slot - 2);
  const y = c => plotH - PADB - (c / max) * (plotH - 14);
  const ns = "http://www.w3.org/2000/svg";
  const svg = document.createElementNS(ns, "svg");
  svg.setAttribute("viewBox", `0 0 ${W} ${H}`); svg.setAttribute("role", "img");
  svg.setAttribute("aria-label", `${g.label}: histogram of win rate over ${g.n} teams`);
  // gridlines: 2 recessive hairlines
  const grid = document.createElementNS(ns, "g"); grid.setAttribute("class", "grid");
  [0.5, 1].forEach(f => { const l = document.createElementNS(ns, "line");
    const yy = y(max * f); l.setAttribute("x1", PADL); l.setAttribute("x2", W - PADR);
    l.setAttribute("y1", yy); l.setAttribute("y2", yy); grid.appendChild(l); });
  svg.appendChild(grid);
  // reference: median untouched real team
  if (ref != null) {
    const rg = document.createElementNS(ns, "g"); rg.setAttribute("class", "ref");
    const x = PADL + (ref * NB + 0.5) * slot;
    const l = document.createElementNS(ns, "line");
    l.setAttribute("x1", x); l.setAttribute("x2", x); l.setAttribute("y1", 2); l.setAttribute("y2", plotH - PADB);
    rg.appendChild(l);
    if (refLabel) { const t = document.createElementNS(ns, "text"); t.setAttribute("x", x + 4); t.setAttribute("y", 10);
      t.textContent = refLabel + " " + ref.toFixed(3); rg.appendChild(t); }
    svg.appendChild(rg);
  }
  // bars
  const peak = g.counts.indexOf(max);
  g.counts.forEach((c, i) => {
    if (!c) return;
    const x = PADL + i * slot + (slot - bw) / 2, top = y(c), h = plotH - PADB - top;
    const r = Math.min(4, h / 2);
    const p = document.createElementNS(ns, "path"); p.setAttribute("class", "bar"); p.setAttribute("tabindex", "0");
    p.setAttribute("d", `M${x},${top + r} a${r},${r} 0 0 1 ${r},-${r} h${bw - 2 * r} a${r},${r} 0 0 1 ${r},${r} v${h - r} h-${bw} z`);
    const show = ev => { tip.style.display = "block";
      tip.textContent = ""; const l1 = document.createElement("div"); l1.textContent = `win rate ${fmtWr(i)}  (${i} of 24)`;
      const l2 = document.createElement("div"); l2.textContent = `${c} teams · ${(100 * c / g.n).toFixed(1)}% of ${g.label}`;
      tip.appendChild(l1); tip.appendChild(l2);
      const px = ev.clientX ?? p.getBoundingClientRect().left, py = ev.clientY ?? p.getBoundingClientRect().top;
      tip.style.left = (px + 12) + "px"; tip.style.top = (py - 34) + "px"; };
    p.addEventListener("pointermove", show); p.addEventListener("focus", show);
    p.addEventListener("pointerleave", () => tip.style.display = "none"); p.addEventListener("blur", () => tip.style.display = "none");
    svg.appendChild(p);
    if (i === peak) { const t = document.createElementNS(ns, "text"); t.setAttribute("class", "peak");
      t.setAttribute("x", x + bw / 2); t.setAttribute("text-anchor", "middle"); t.setAttribute("y", top - 3); t.textContent = c; svg.appendChild(t); }
  });
  if (withAxis) {
    const ax = document.createElementNS(ns, "g"); ax.setAttribute("class", "axis");
    [0, 6, 12, 18, 24].forEach(i => { const t = document.createElementNS(ns, "text");
      t.setAttribute("x", PADL + (i + 0.5) * slot); t.setAttribute("y", H - 3); t.setAttribute("text-anchor", "middle");
      t.textContent = (i / NB).toFixed(2); ax.appendChild(t); });
    svg.appendChild(ax);
  }
  return svg;
}

const REDRAW = [];
function panel(g, ref, refLabel, cls, withAxis) {
  const d = document.createElement("div"); d.className = "panel " + cls;
  const lab = document.createElement("div"); lab.className = "lab";
  const b = document.createElement("b"); b.textContent = g.label; lab.appendChild(b);
  const s = document.createElement("small"); s.textContent = `n ${g.n} · mean ${g.mean.toFixed(3)}` + (g.median != null ? ` · median ${g.median.toFixed(3)}` : ""); lab.appendChild(s);
  d.appendChild(lab);
  const holder = document.createElement("div"); holder.className = "holder"; d.appendChild(holder);
  const draw = () => { W = Math.max(280, Math.round(holder.getBoundingClientRect().width || 760));
    holder.textContent = ""; holder.appendChild(panelSVG(g, ref, refLabel, withAxis)); };
  REDRAW.push(draw); return d;
}

function table(sec) {
  const t = document.createElement("table");
  const thead = document.createElement("thead"), tr = document.createElement("tr");
  ["win rate", "wins /24", ...sec.groups.map(g => g.key)].forEach(h => { const th = document.createElement("th"); th.textContent = h; tr.appendChild(th); });
  thead.appendChild(tr); t.appendChild(thead);
  const tb = document.createElement("tbody");
  for (let i = 0; i <= NB; i++) { const r = document.createElement("tr");
    [fmtWr(i), String(i), ...sec.groups.map(g => String(g.counts[i]))].forEach(v => { const td = document.createElement("td"); td.textContent = v; r.appendChild(td); });
    tb.appendChild(r); }
  t.appendChild(tb); return t;
}

const root = $("#root");
DATA.forEach(sec => {
  const s = document.createElement("section");
  const h = document.createElement("h2"); h.textContent = `${sec.title} — ${sec.total.n.toLocaleString()} labelled teams`; s.appendChild(h);
  const p = document.createElement("p"); p.className = "sub"; p.textContent = sec.sub; s.appendChild(p);
  const chart = document.createElement("div"); chart.className = "chart";
  chart.appendChild(panel({label: "all teams in this dataset", n: sec.total.n, counts: sec.total.counts, mean: sec.total.mean}, sec.ref, sec.ref_label, "total", false));
  sec.groups.forEach((g, i) => chart.appendChild(panel(g, sec.ref, null, "", i === sec.groups.length - 1)));
  s.appendChild(chart);
  const tv = table(sec); tv.className = "hidden"; s.appendChild(tv);
  const f = document.createElement("p"); f.className = "foot";
  f.textContent = `The vertical rule marks the ${sec.ref_label} (${sec.ref.toFixed(3)}). Each panel's y-axis is its own; the number above the tallest bar is that panel's peak count.`;
  s.appendChild(f); root.appendChild(s);
});
function setView(tbl) {
  document.querySelectorAll(".chart").forEach(e => e.classList.toggle("hidden", tbl));
  document.querySelectorAll("table").forEach(e => e.classList.toggle("hidden", !tbl));
  $("#bChart").setAttribute("aria-pressed", String(!tbl)); $("#bTable").setAttribute("aria-pressed", String(tbl));
}
$("#bChart").onclick = () => setView(false); $("#bTable").onclick = () => setView(true);
REDRAW.forEach(f => f());
let rt; addEventListener("resize", () => { clearTimeout(rt); rt = setTimeout(() => REDRAW.forEach(f => f()), 120); });
</script></body></html>
"""
OUT.write_text(HTML.replace("__DATA__", json.dumps(SECTIONS)))
print(f"wrote {OUT} with {len(SECTIONS)} section(s): {[s['title'] for s in SECTIONS]}")
