"""Generate the two arms that close the goal:

  model_edit  - a real corpus team with ONE candidate regenerated by the diffusion
                model (unconditioned). Tests whether the learned local move beats a
                random slot copy ON WIN RATE, which is the question a search cares
                about. slotcopy already measured 0.4199.
  model_style - the same move, but conditioned on the source team's own playstyle
                with guidance. Tests whether steering HELPS or COSTS win rate -
                property (2) combined with f, which nothing has yet measured.

Both start from real teams, so unlike from-scratch generation they are in the range
where win rate can actually discriminate.
"""
import sys, json
from collections import defaultdict
from pathlib import Path
import numpy as np, torch
from corpus import load_corpus, norm, STATS
from encode import Vocab, Legality, canon, NF, NSLOT
import diffusion as D
from propose import Validator, slot_to_text

n_want = int(sys.argv[1]) if len(sys.argv) > 1 else 16
seed   = int(sys.argv[2]) if len(sys.argv) > 2 else 0
guid   = float(sys.argv[3]) if len(sys.argv) > 3 else 2.0
rng = np.random.default_rng(seed); torch.manual_seed(seed)

teams, V, L, X, Y = D.load_all()
model = D._load(V); C = D.Constraints(V, L)
look = {}
for t in teams:
    for s in t:
        look[norm(s["species"])] = s["species"]; look[norm(s["ability"])] = s["ability"]
        if s["item"]: look[norm(s["item"])] = s["item"]
        for m in s["moves"]: look[norm(m)] = m
        if s["nature"]: look[norm(s["nature"])] = s["nature"]

def render(row, base):
    """Row -> Showdown paste. Each slot keeps the SOURCE team's spread, so this arm
    differs from slotcopy only in which candidate/set the model chose."""
    slots = []
    for i in range(NSLOT):
        b = i * NF
        g = lambda j: V.decode_field(b + j, int(row[b + j]))
        mv = [look.get(g(3+j), g(3+j)) for j in range(4) if g(3+j) and g(3+j) != "[MASK]"]
        slots.append(dict(species=look.get(g(0), g(0)), item=look.get(g(2), g(2)),
                          ability=look.get(g(1), g(1)), nature=look.get(g(7), g(7)),
                          moves=mv, evs=base[i]["evs"]))
    return "\n\n".join(slot_to_text(s) for s in slots) + "\n"

out = Path("/tmp/vgc-pilot/proposals"); out.mkdir(exist_ok=True)
val = Validator()
for arm, styled in [("modeledit", False), ("modelstyle", True)]:
    for f in out.glob(f"{arm}_*.txt"): f.unlink()
    kept = tries = 0
    while kept < n_want and tries < 600:
        tries += 1
        ti = int(rng.integers(0, len(teams)))
        base = canon(teams[ti])
        style = D.STYLES[D.style_of(base)] if styled else "none"
        g = guid if (styled and style != "none") else 1.0
        s = int(rng.integers(0, NSLOT))
        m = np.zeros((1, D.COLS), bool); m[0, s*NF:(s+1)*NF] = True
        row = D.sample_constrained(model, C, 1, style=style, guidance=g, temp=1.0,
                                   x0=torch.tensor(X[ti][None, :]),
                                   mask=torch.tensor(m)).cpu().numpy()[0]
        if (row == X[ti]).all():          # a no-op is not a proposal
            continue
        txt = render(row, base)
        if val(txt) is None:
            (out/f"{arm}_{kept}.txt").write_text(txt); kept += 1
    print(f"{arm}: kept {kept}/{tries} ({kept/max(tries,1):.1%} Showdown-valid, non-noop)")
val.close()
