"""Build a stratified (team, win-rate) dataset spanning the whole quality range.

Random legal teams were measured at median 0.000 — no signal. Real teams sit at
0.475. The useful middle is reached by REALISTIC search moves, not random
corruption, so the strata are the moves a search would actually make:

  real        a corpus team, untouched                        ~0.475
  shuffled    its spreads swapped within species              ~0.414
  slotcopy1/2/3   1, 2 or 3 candidates pasted from other real teams
  modeledit   1 candidate regenerated by the model            ~0.406
  invent      the whole team from the model, constrained      ~0.093
  random      random legal team                               ~0.011

Every team is checked by Showdown before it is kept.
"""
import json, sys
from collections import defaultdict
from pathlib import Path
import numpy as np, torch
from corpus import load_corpus, norm, STATS
from encode import Vocab, Legality, canon, NF, NSLOT
import diffusion as D
from propose import Validator, team_to_text, slot_to_text
from random_team import build_tables, one_team

def main():
    per  = int(sys.argv[1]) if len(sys.argv) > 1 else 300
    seed = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    rng = np.random.default_rng(seed); torch.manual_seed(seed)
    out = Path("/tmp/vgc-pilot/strata"); out.mkdir(exist_ok=True)
    for f in out.glob("*.txt"): f.unlink()

    teams, V, L, X, Y = D.load_all()
    model = D._load(V); C = D.Constraints(V, L)
    RT = build_tables()
    look, spreads, by_sp = {}, defaultdict(list), defaultdict(list)
    for t in teams:
        for s in t:
            look[norm(s["species"])] = s["species"]; look[norm(s["ability"])] = s["ability"]
            if s["item"]: look[norm(s["item"])] = s["item"]
            for m in s["moves"]: look[norm(m)] = m
            if s["nature"]: look[norm(s["nature"])] = s["nature"]
            spreads[norm(s["species"])].append(dict(s["evs"]))
            by_sp[norm(s["species"])].append(s)

    def row_slots(row, base=None):
        o = []
        for i in range(NSLOT):
            b = i * NF
            g = lambda j: V.decode_field(b + j, int(row[b + j]))
            mv = [look.get(g(3+j), g(3+j)) for j in range(4) if g(3+j) and g(3+j) != "[MASK]"]
            sp = g(0)
            ev = base[i]["evs"] if base else (spreads.get(sp) or [{s:0 for s in STATS}])[
                 int(rng.integers(0, len(spreads.get(sp, [1]))))]
            o.append(dict(species=look.get(sp,sp), item=look.get(g(2),g(2)),
                          ability=look.get(g(1),g(1)), nature=look.get(g(7),g(7)),
                          moves=mv, evs=ev))
        return o

    def clauses_ok(sl):
        b=[norm(s["species"]) for s in sl]; it=[norm(s["item"]) for s in sl if s["item"]]
        return len(set(b))==6 and len(set(it))==len(it)

    val = Validator(); meta = {}
    def emit(tag, sl):
        if not clauses_ok(sl): return False
        txt = team_to_text(sl)
        if val(txt) is not None: return False
        n = meta_count[tag]; p = out/f"{tag}_{n:05d}.txt"
        p.write_text(txt); meta[str(p)] = {"stratum": tag}; meta_count[tag] += 1
        return True
    meta_count = defaultdict(int)

    STRATA = ["real","shuffled","slotcopy1","slotcopy2","slotcopy3","modeledit","invent","random"]
    for tag in STRATA:
        tries = 0
        while meta_count[tag] < per and tries < per*30:
            tries += 1
            if tag == "random":
                sl = one_team(RT, rng); 
                if sl: emit(tag, sl)
                continue
            if tag == "invent":
                row = D.sample_constrained(model, C, 1, "none", 1.0, 1.0).cpu().numpy()[0]
                emit(tag, row_slots(row)); continue
            ti = int(rng.integers(0, len(teams))); base = [dict(s) for s in canon(teams[ti])]
            if tag == "real":
                emit(tag, base)
            elif tag == "shuffled":
                for s in base:
                    pool = spreads[norm(s["species"])]
                    if len(pool) > 1: s["evs"] = pool[int(rng.integers(0, len(pool)))]
                emit(tag, base)
            elif tag.startswith("slotcopy"):
                k = int(tag[-1])
                for i in rng.choice(6, k, replace=False):
                    d = canon(teams[int(rng.integers(0, len(teams)))])
                    base[int(i)] = dict(d[int(rng.integers(0, 6))])
                emit(tag, base)
            elif tag == "modeledit":
                s = int(rng.integers(0, NSLOT))
                m = np.zeros((1, D.COLS), bool); m[0, s*NF:(s+1)*NF] = True
                row = D.sample_constrained(model, C, 1, "none", 1.0, 1.0,
                        x0=torch.tensor(X[ti][None,:]), mask=torch.tensor(m)).cpu().numpy()[0]
                emit(tag, row_slots(row, base))
        print(f"  {tag:10s} {meta_count[tag]:4d} teams ({meta_count[tag]/max(tries,1):.0%} accepted)", flush=True)
    val.close()
    json.dump(meta, open("/tmp/vgc-pilot/strata_meta.json","w"))
    print(f"total {sum(meta_count.values())} teams across {len(STRATA)} strata")

if __name__ == "__main__":
    main()
