"""Score generated teams with Showdown's OWN TeamValidator, not our hand-built
oracle. This is the authoritative gate: a team the validator rejects cannot be
battled, so it cannot have a win rate at all.

Stat Points are not generated by the model, so each slot inherits a spread drawn
from a corpus slot of the same species. That choice is documented, not hidden:
the spread is real data, and it is applied identically to every arm.
"""
import argparse, json, random
from collections import Counter, defaultdict
import numpy as np, torch
from corpus import load_corpus, norm, STATS
from encode import Vocab, Legality, team_fields, canon, FIELDS, NF, NSLOT
import diffusion as D
from propose import Validator, slot_to_text

def build_lookup(teams):
    L = {}
    for t in teams:
        for s in t:
            L[norm(s["species"])] = s["species"]; L[norm(s["ability"])] = s["ability"]
            if s["item"]: L[norm(s["item"])] = s["item"]
            for m in s["moves"]: L[norm(m)] = m
            if s["nature"]: L[norm(s["nature"])] = s["nature"]
    return L

def spreads_by_species(teams):
    d = defaultdict(list)
    for t in teams:
        for s in t:
            d[norm(s["species"])].append(dict(s["evs"]))
    return d

def row_to_paste(V, row, look, spreads, rng):
    slots = []
    for i in range(NSLOT):
        b = i * NF
        g = lambda j: V.decode_field(b + j, int(row[b + j]))
        sp = g(0)
        mv = [look.get(g(3+j), g(3+j)) for j in range(4) if g(3+j) and g(3+j) != "[MASK]"]
        pool = spreads.get(sp) or [{s: 0 for s in STATS}]
        slots.append(dict(species=look.get(sp, sp), item=look.get(g(2), g(2)),
                          ability=look.get(g(1), g(1)), nature=look.get(g(7), g(7)),
                          moves=mv, evs=pool[rng.integers(0, len(pool))]))
    return "\n\n".join(slot_to_text(s) for s in slots) + "\n"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=64)
    ap.add_argument("--style", default="none")
    ap.add_argument("--guidance", type=float, default=1.0)
    ap.add_argument("--temp", type=float, default=1.0)
    ap.add_argument("--mode", default="scratch", choices=["scratch", "edit"])
    ap.add_argument("--k", type=int, default=8)
    ap.add_argument("--seed", type=int, default=0)
    a = ap.parse_args()
    rng = np.random.default_rng(a.seed); torch.manual_seed(a.seed)
    teams, V, L, X, Y = D.load_all()
    look = build_lookup(teams); spreads = spreads_by_species(teams)
    model = D._load(V); C = D.Constraints(V, L)

    if a.mode == "scratch":
        x = D.sample_constrained(model, C, a.n, a.style, a.guidance, a.temp).cpu().numpy()
        src = None
    else:
        si = rng.integers(0, len(X), a.n); src = X[si]
        m = np.zeros((a.n, D.COLS), bool)
        for b in range(a.n):
            s = rng.integers(0, NSLOT); m[b, s*NF:(s+1)*NF] = True
        x = D.sample_constrained(model, C, a.n, a.style, a.guidance, a.temp,
                                 x0=torch.tensor(src), mask=torch.tensor(m)).cpu().numpy()

    val = Validator()
    ok, errs, texts = 0, Counter(), []
    for i in range(a.n):
        txt = row_to_paste(V, x[i], look, spreads, rng)
        e = val(txt)
        if e is None: ok += 1; texts.append(txt)
        else:
            key = ("mega/item" if "mega" in e.lower() or "does not exist" in e.lower()
                   else "learnset" if "can't learn" in e.lower() or "cannot learn" in e.lower()
                   else "ability" if "ability" in e.lower()
                   else "statpoints" if "stat point" in e.lower() or "ev" in e.lower()
                   else "other")
            errs[key] += 1
            if len(errs) <= 3 and errs[key] == 1: print("  example error:", e[:150])
    val.close()
    our = sum(L.legal([V.decode_field(c, int(x[i][c])) for c in range(D.COLS)]) for i in range(a.n))
    print(f"\nmode={a.mode} style={a.style} guidance={a.guidance} temp={a.temp} n={a.n}")
    print(f"  our oracle says legal : {our}/{a.n} ({our/a.n:.1%})")
    print(f"  SHOWDOWN says legal   : {ok}/{a.n} ({ok/a.n:.1%})")
    print(f"  showdown rejects      : {dict(errs.most_common())}")
    Path = __import__("pathlib").Path
    out = Path("/tmp/vgc-pilot/valid_gen"); out.mkdir(exist_ok=True)
    for f in out.glob("*.txt"): f.unlink()
    for i, t in enumerate(texts): (out / f"gen_{i}.txt").write_text(t)
    print(f"  wrote {len(texts)} Showdown-valid teams to {out}")

if __name__ == "__main__":
    main()
