/* Fixed explanatory example and actual browser-generated trace share the same cards. */
(()=>{'use strict';
const host=document.querySelector('.team-reveal'),example=JSON.parse(document.querySelector('#team-reveal-data').textContent),range=host.querySelector('input[type="range"]');
const status=host.querySelector('.generation-status'),errorBox=host.querySelector('.generation-errors'),generateButton=host.querySelector('.generate-team'),stopButton=host.querySelector('.stop-generation');
const validationLink=host.querySelector('a[href="./team-example-validation.json"]');
let frames=[],result=example,mode='example',worker=null,busy=false,attemptsFrames=[],attempt=0,downloadURL=null,traceURL=null;
const spriteMap={Excadrill:'excadrill.png',Tyranitar:'tyranitar.png',Staraptor:'staraptor.png',Basculegion:'basculegion.png',Sinistcha:'sinistcha.png',Raichu:'raichu.png'};
fetch('./model/sprites.json').then(r=>r.ok?r.json():null).then(d=>{Object.entries(d?.sprites||{}).forEach(([key,path])=>{spriteMap[key]=path.split('/').pop()});render()}).catch(()=>{});
fetch('./sprites/sources.json').then(r=>r.ok?r.json():null).then(d=>{d?.assets?.forEach(a=>{spriteMap[a.species||a.file.replace('.png','')]=a.file});render()}).catch(()=>{});
const labels=['All fields masked','Reveal species','Reveal abilities and items','Reveal moves','Reveal natures','Fill stat points','Check the completed example'];
function exampleFrames(){return labels.map((label,step)=>({label,kind:step===6?'validation':step===5?'spreads':'example',valid:step===6?example.validated:undefined,validationErrors:[],team:example.team.map(s=>({...s,species:step>=1?s.species:null,ability:step>=2?s.ability:null,item:step>=2?s.item:null,moves:s.moves.map(m=>step>=3?m:null),nature:step>=4?s.nature:null,statPoints:step>=5?s.statPoints:null,level:step>=5?s.level:null}))}))}
const cards=d3.select(host.querySelector('.team-cards')).selectAll('article').data(Array.from({length:6},(_,i)=>({slot:i+1}))).join('article').attr('class','team-slot');
cards.append('div').attr('class','slot-number').text(d=>`Slot ${d.slot}`);
const spriteFrames=cards.append('div').attr('class','sprite-frame').attr('aria-hidden','true');
spriteFrames.append('img').attr('class','pokemon-sprite').attr('alt','').attr('width',96).attr('height',96).attr('draggable','false').on('error',function(){this.closest('.team-slot').classList.add('sprite-unavailable')});
spriteFrames.append('span').attr('class','sprite-mask').text('?');spriteFrames.append('span').attr('class','sprite-initials');cards.append('h3');
const fields=['Ability','Item','Moves','Nature','Stat Points','Level'];cards.each(function(){const el=d3.select(this);fields.forEach((label,i)=>{const field=el.append('div').attr('class','team-field'+(i===2?' moves-field':'')).attr('data-field',i);field.append('span').attr('class','field-label').text(label);field.append('span').attr('class','field-value')})});
function text(el,value){el.textContent=value==null?'[masked]':value===''?'(none)':value;el.classList.toggle('masked',value==null)}
function setBusy(value){busy=value;generateButton.disabled=value;stopButton.hidden=!value;range.disabled=value;host.querySelector('.show-example').disabled=value;host.querySelector('.reveal-reset').disabled=value;render()}
function render(){if(!frames.length)return;const step=Math.min(Number(range.value),frames.length-1),frame=frames[step];range.max=String(frames.length-1);host.querySelector('.reveal-stage').textContent=frame.label;host.querySelector('.reveal-count').textContent=`${step} / ${frames.length-1}`;range.setAttribute('aria-valuetext',`${step} of ${frames.length-1}: ${frame.label}`);
 cards.each(function(_,i){const s=frame.team[i],el=this;el.classList.toggle('species-revealed',Boolean(s.species));text(el.querySelector('h3'),s.species);const file=s.species&&(spriteMap[s.species]||spriteMap[s.species.toLowerCase().replace(/[^a-z0-9]/g,'')]);const img=el.querySelector('.pokemon-sprite');el.classList.toggle('sprite-unavailable',!file);if(file&&img.getAttribute('src')!=='./sprites/'+file)img.src='./sprites/'+file;el.querySelector('.sprite-initials').textContent=s.species?s.species.slice(0,2).toUpperCase():'';const values=[s.ability,s.item,s.moves?.some(Boolean)?s.moves.map(m=>m||'[masked]').join(' / '):null,s.nature,s.statPoints?Object.entries(s.statPoints).filter(([,v])=>v).map(([k,v])=>`${v} ${k}`).join(' / '):null,s.level];values.forEach((value,j)=>text(el.querySelector(`[data-field="${j}"] .field-value`),value))});
 const checked=frame.kind==='validation',passed=checked&&frame.valid;const badge=host.querySelector('.validation-status');badge.textContent=passed?(mode==='live'?'✓ Browser validation passed':'✓ Validated example'):checked?'Validation failed':frame.kind==='spreads'?'Complete · not yet checked':'Partial team · not validated';badge.classList.toggle('passed',Boolean(passed));
 host.querySelector('.reveal-prev').disabled=busy||step===0;host.querySelector('.reveal-next').disabled=busy||step===frames.length-1;
 host.querySelector('.reveal-explanation').textContent=mode==='example'?'Illustrative reveal of a fixed corpus example; not a model sampling trace.':frame.kind==='sample'?(step===0?'All 48 fields start masked. Each model step samples one field.':'Recorded model step: one field was sampled from probabilities constrained by the choices already made.'):frame.kind==='spreads'?'Stat Points are copied from same-species corpus examples after model sampling.':passed?'The generated team passed the format validator. Its battle strength has not been measured.':'The generated team did not pass the format validator.';
 host.querySelector('.reveal-export').hidden=!checked||busy;host.querySelector('.reveal-provenance').hidden=!checked||busy;
 if(checked&&result){validationLink.href=mode==='example'?'./team-example-validation.json':'./runtime/VALIDATOR.md';validationLink.textContent=mode==='example'?'Example validation record':'Browser validator details';host.querySelector('.reveal-provenance').textContent=mode==='example'?example.provenance:`Generated here with seed ${result.seed}, no win-rate conditioning and temperature 1. ${result.attempts?.length||1} candidate attempt(s), each checked by the pinned format validator. The slider replays the final attempt’s actual 48 sampled fields, copied spreads, and validation.`;host.querySelector('.reveal-export pre').textContent=result.showdown||'';}
}
function setDownloads(){if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=URL.createObjectURL(new Blob([result.showdown||''],{type:'text/plain'}));host.querySelector('.download-team').href=downloadURL;if(traceURL)URL.revokeObjectURL(traceURL);const traceLink=host.querySelector('.download-trace');traceLink.hidden=mode!=='live';if(mode==='live'){traceURL=URL.createObjectURL(new Blob([JSON.stringify({result,attempts:attemptsFrames},null,2)],{type:'application/json'}));traceLink.href=traceURL;}}
const traceLink=document.createElement('a');traceLink.className='download-team download-trace';traceLink.download='pokemon-diffusion-trace.json';traceLink.textContent='Download sampling trace';traceLink.hidden=true;host.querySelector('.export-actions').append(traceLink);
function fixedExample(){mode='example';result=example;frames=exampleFrames();range.max=6;range.value=0;errorBox.hidden=true;status.textContent='The slider shows a fixed example. Generate a new team to run the model in this browser (about 29 MB on first use).';setDownloads();render()}
function fail(message){setBusy(false);errorBox.textContent=message;errorBox.hidden=false;status.textContent='Generation stopped. Any partial fields shown are not a validated team.';if(worker){worker.terminate();worker=null}}
function createWorker(){worker=new Worker('./sampler-worker.js');worker.onmessage=({data:d})=>{if(d.type==='status')status.textContent=d.message;else if(d.type==='attempt'){attempt=d.attempt;frames=[];attemptsFrames.push({attempt,frames});range.value=0;status.textContent=`Sampling candidate ${attempt} of at most ${d.maxAttempts}…`}else if(d.type==='frame'){frames.push(d.frame);range.max=frames.length-1;range.value=frames.length-1;render();if(d.frame.kind==='sample')status.textContent=`Candidate ${attempt}: ${Math.min(frames.length-1,48)} of 48 fields sampled in your browser.`}else if(d.type==='complete'){result=d;setBusy(false);setDownloads();render();status.textContent=d.valid?`Generated and validated in your browser. ${d.attempts.length} candidate attempt(s); ${d.seconds.toFixed(1)} seconds for the final attempt. Scrub to inspect its actual sampled states.`:'Five candidates failed validation. The last candidate and all attempt traces remain available for inspection.';if(d.attempts.some(a=>!a.valid)){errorBox.hidden=false;errorBox.textContent=d.attempts.filter(a=>!a.valid).map(a=>`Attempt ${a.attempt} rejected: ${a.validationErrors.join('; ')}`).join('\n')}}else if(d.type==='error')fail(d.message)};worker.onerror=e=>fail(e.message||'The browser could not start model inference.');}
generateButton.addEventListener('click',()=>{if(location.protocol==='file:'){errorBox.hidden=false;errorBox.textContent='Browser inference needs an HTTP preview. Start the local preview server described in README.md, then open its address.';return}mode='live';result=null;attemptsFrames=[];frames=[{...exampleFrames()[0],kind:'sample',label:'Loading model · all fields masked'}];range.max=0;range.value=0;errorBox.hidden=true;host.querySelector('.copy-status').textContent='';setBusy(true);status.textContent='Starting browser inference…';if(!worker)createWorker();worker.postMessage({type:'generate',seed:crypto.getRandomValues(new Uint32Array(1))[0]})});
stopButton.addEventListener('click',()=>fail('Stopped by you. Generate again to start a new candidate.'));host.querySelector('.show-example').addEventListener('click',fixedExample);
range.addEventListener('input',render);host.querySelector('.reveal-prev').addEventListener('click',()=>{range.value=Math.max(0,Number(range.value)-1);render()});host.querySelector('.reveal-next').addEventListener('click',()=>{range.value=Math.min(frames.length-1,Number(range.value)+1);render()});host.querySelector('.reveal-reset').addEventListener('click',()=>{range.value=0;render()});
host.querySelector('.copy-team').addEventListener('click',async()=>{const feedback=host.querySelector('.copy-status');try{await navigator.clipboard.writeText(result.showdown);feedback.textContent='Team copied.'}catch{feedback.textContent='Select the team text below to copy it.';const selection=window.getSelection(),r=document.createRange();r.selectNodeContents(host.querySelector('.reveal-export pre'));selection.removeAllRanges();selection.addRange(r)}});
window.addEventListener('pagehide',()=>{worker?.terminate();if(downloadURL)URL.revokeObjectURL(downloadURL);if(traceURL)URL.revokeObjectURL(traceURL)},{once:true});fixedExample();
})();
