const {chromium}=require('/Users/ramiismael/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1240,height:1150},deviceScaleFactor:2});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.join(__dirname,'index.html'));await page.screenshot({path:path.join(__dirname,'preview.png'),fullPage:true});
for(const mode of ['sun','rain']){await page.locator(`button[data-mode="${mode}"]`).click();for(const member of ['venusaur','archaludon','basculegion']){await page.locator(`[data-pokemon="${member}"]`).click();if(await page.locator('#context-tag').textContent()!==mode.toUpperCase())throw Error('Wrong mode');if(!await page.locator('#chain-result').textContent())throw Error('No explanation')}}
await page.locator('button[data-mode="sun"]').click();if(await page.locator('#basculegion-effect').textContent()!=='Water damage ×0.5')throw Error('Wrong sun mechanic');await page.locator('[data-pokemon="venusaur"]').click();await page.waitForTimeout(700);await page.screenshot({path:path.join(__dirname,'preview-sun.png'),fullPage:true});
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('button[data-mode="rain"]').focus();await page.keyboard.press('Enter');if(await page.evaluate(()=>document.getAnimations().length))throw Error('Reduced motion failed');
await page.locator('#play').click();await page.waitForTimeout(3300);await page.locator('button[data-mode="rain"]').click();await page.waitForTimeout(3300);if(await page.locator('.map').getAttribute('data-mode')!=='rain')throw Error('Interruption failed');
await page.locator('#play').click();await page.waitForTimeout(13100);if(await page.locator('#play').getAttribute('aria-label')!=='Play weather change animation')throw Error('Playback failed');
for(const width of [320,390,700,950,1240]){await page.setViewportSize({width,height:1000});for(const mode of ['sun','rain']){await page.locator(`button[data-mode="${mode}"]`).click();if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error(`Overflow ${width}`)}if(width===390)await page.screenshot({path:path.join(__dirname,'preview-mobile.png'),fullPage:true})}
if(errors.length)throw Error(errors.join('\n'));console.log('PASS: six interaction states, weather mechanics, keyboard/reduced motion, interruptible and complete playback, no overflow at five widths, no JavaScript errors.');await browser.close()})();
