(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion:reduce)');let mode='rain',selected='basculegion',keyboard=false,timer=null,playing=false;
const copy={
 rain:{venusaur:{title:'The same teammate loses its speed bonus.',result:'Venusaur’s Speed ×1',body:'Chlorophyll doubles Speed in sun. In rain, that bonus is inactive—even though Venusaur and its ability have not changed.',boost:false},archaludon:{title:'A teammate removes the charging turn.',result:'Archaludon’s Electro Shot: no charge',body:'Rain lets Electro Shot attack on the turn it is selected, rather than charging first. Pelipper changes how quickly this move can deliver damage.',boost:true},basculegion:{title:'A rain setter changes a teammate’s attack.',result:'Basculegion’s Wave Crash ×1.5',body:'The weather multiplier comes from Pelipper’s ability. Basculegion does not create this advantage alone.',boost:true}},
 sun:{venusaur:{title:'A teammate activates a different role.',result:'Venusaur’s Speed ×2',body:'Drought creates sun; Chlorophyll responds by doubling Venusaur’s Speed. The advantage depends on the setter, the teammate, and its ability together.',boost:true},archaludon:{title:'One mode removes another mode’s shortcut.',result:'Archaludon’s Electro Shot: charge first',body:'Outside rain, Electro Shot needs a charging turn before it attacks. This linked team uses Leftovers, so it has no Power Herb to bypass that turn.',boost:false},basculegion:{title:'A teammate can weaken your own attack.',result:'Basculegion’s Wave Crash ×0.5',body:'Sun halves Water-type damage. Basculegion keeps the same move and stats, yet this part of its contribution is weaker in the sun plan.',boost:false}}
};
function stop(){clearTimeout(timer);timer=null;playing=false;$('#play').textContent='▶ Watch the change';$('#play').setAttribute('aria-label','Play weather change animation')}
function animate(){document.getAnimations().forEach(a=>a.cancel());if(keyboard||reduced.matches)return;$('#detail').animate([{opacity:.35,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:240,easing:'cubic-bezier(.23,1,.32,1)'});const edge=$(`[data-edge="${selected}"]`);edge.animate([{opacity:.18},{opacity:1}],{duration:650,easing:'cubic-bezier(.23,1,.32,1)'});$('.weather').animate([{transform:'scale(.95)',opacity:.6},{transform:'scale(1)',opacity:1}],{duration:400,easing:'cubic-bezier(.23,1,.32,1)'})}
function render(motion=true){const sun=mode==='sun',d=copy[mode][selected];$('.map').dataset.mode=mode;$$('[data-mode]').filter(e=>e.tagName==='BUTTON').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.mode===mode)));$('.weather-icon').textContent=sun?'☀':'☂';$('#weather-name').textContent=sun?'Sun':'Rain';$('#context-tag').textContent=mode.toUpperCase();$('#charizard-effect').textContent=sun?'Heat Wave ×1.5':'Heat Wave ×0.5';$('#pelipper-effect').textContent=sun?'Fire Weather Ball ×1.5':'Water Weather Ball ×1.5';$('#venusaur-effect').textContent=sun?'Speed ×2':'Speed ×1';$('#archaludon-effect').textContent=sun?'Charge, then attack':'No charging turn';$('#basculegion-effect').textContent=sun?'Water damage ×0.5':'Water damage ×1.5';$$('[data-pokemon]').forEach(e=>{e.setAttribute('aria-pressed',String(e.dataset.pokemon===selected));e.classList.toggle('boost',copy[mode][e.dataset.pokemon].boost)});$$('[data-edge]').forEach(e=>{e.classList.toggle('boost',copy[mode][e.dataset.edge].boost);e.classList.toggle('focus',e.dataset.edge===selected)});$('#detail-title').textContent=d.title;$('#detail-body').textContent=d.body;$('#chain-setter').textContent=sun?'Mega Charizard Y':'Pelipper';$('#chain-weather').textContent=sun?'Drought → sun':'Drizzle → rain';$('#chain-result').textContent=d.result;$('#tradeoff').textContent=sun?'Sun speeds up Venusaur while halving Basculegion’s Water-type damage. One change has different consequences across the team.':'The same rain halves Charizard’s Fire-type damage. A useful combination can still contain a conflict.';$('#status').textContent=`${sun?'Sun':'Rain'}. ${d.result}.`;if(motion)animate()}
$$('button[data-mode]').forEach(b=>b.addEventListener('click',()=>{stop();mode=b.dataset.mode;render()}));$$('[data-pokemon]').forEach(b=>b.addEventListener('click',()=>{stop();selected=b.dataset.pokemon;render()}));
$('#play').addEventListener('click',()=>{if(playing){stop();return}playing=true;mode='sun';selected='venusaur';render();$('#play').textContent='Ⅱ Pause';$('#play').setAttribute('aria-label','Pause weather change animation');let i=0;const frames=[['sun','basculegion'],['rain','basculegion'],['rain','archaludon']];function next(){timer=setTimeout(()=>{if(i===frames.length){stop();return}[mode,selected]=frames[i++];render();next()},3200)}next()});
document.addEventListener('keydown',()=>{keyboard=true;document.documentElement.classList.add('instant');document.getAnimations().forEach(a=>a.cancel())});document.addEventListener('pointerdown',()=>{keyboard=false;document.documentElement.classList.remove('instant')});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});reduced.addEventListener('change',()=>document.getAnimations().forEach(a=>a.cancel()));render(false);
})();
